FROM python:3.12-slim

WORKDIR /app

COPY stream_engine/requirements.txt /app/stream_engine/requirements.txt
RUN pip install --no-cache-dir -r /app/stream_engine/requirements.txt

COPY . /app

EXPOSE 9000

ENV HANDLER_IMPORT=""
ENV STORE_BASE_URL="http://engine:8000"

CMD ["uvicorn", "handler_service.app:app", "--host", "0.0.0.0", "--port", "9000"]

